---
title: "Test_Institut_Jerome"
output: html_document
date: "2025-09-29"
---
```{r}
getwd()
## Packages & Librairies
{
library(DBI)
library(duckdb)
library(gtsummary)
library(dplyr)
}
```

---
Etablir une connexion à Duckdb ainsi que la requête pour récupérer toutes les variables de notre BDD
---

```{r}
## Connexion à la base DuckDB existante
cnx <- dbConnect(duckdb::duckdb(), dbdir = "cancers_idf.duckdb")

## Exécuter une requête SQL pour récupérer toutes les données (ou une sélection)
requete <- "SELECT * FROM cancers"

## Récupérer les données dans un data frame
data <- dbGetQuery(cnx, requete)

dbDisconnect(cnx, shutdown=TRUE) ## se déconnecter de la bdd

```

---
structure de notre jeu de données
---
```{r}
str(data)
```

---
Créer un tableau descriptif pour les variables (numériques et catégorielles)
---
```{r}
table_describe <- tbl_summary(
data,
missing = "no", # Ne pas afficher les valeurs manquantes dans le tableau
statistic = list(
all_categorical() ~ "{n} ({p}%)", # Pour les variables catégorielles, afficher n et %
all_continuous2() ~ c(
      "{mean} ({sd})",          # Moyenne (écart-type)
      "{median}",               # Médiane
      "{min}",                  # Minimum
      "{max}"                   # Maximum # Pour continous2, afficher plusieurs stat
)
)
)


```

